import { ConnectButton } from "@rainbow-me/rainbowkit";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        <h1 className={styles.title}>
          <a href="">Welcome to DONATE2DEVS</a> +{" "}
          <a href="">Donate with any erc20 tokens</a> +{" "}
          <a href="">As simple as connect and donate.</a>
        </h1>

        <h2>Developers</h2>
        <table className="developer-table">
          <thead>
            <tr>
              <th>Name</th>

              <th>social</th>

              <th>Role</th>

              <th>erc address</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td className="table-name">D Lancashire</td>
              <td>
                <a href="https://github.com/trevelyan">GitHub</a>
              </td>
              <td>
                <ul>
                  <li>Founder</li>
                  <li>Red Square</li>
                  <li>Arcade</li>
                </ul>
              </td>
              <td>0x94d0b12c651f281566bb415889f703e112027c8a</td>
            </tr>
            <tr>
              <td className="table-name">R Parris</td>
              <td>
                <a href="https://github.com/arpee">GitHub</a>
              </td>
              <td>
                <ul>
                  <li>Founder</li>
                  <li>Redsquare</li>
                  <li>tech</li>
                </ul>
              </td>
              <td></td>
            </tr>
            <tr>
              <td className="table-name">escapedcat</td>
              <td>
                <a href="https://github.com/escapedcat?tab=repositories">
                  GitHub
                </a>
              </td>
              <td>
                <ul>
                  <li>Python</li>
                  <li>Django</li>
                  <li>PostgreSQL</li>
                </ul>
              </td>
              <td></td>
            </tr>
            <td className="table-name">Ramses</td>
            <td>
              <a href="https://github.com/Ramcas42">GitHub</a>
            </td>
            <td>
              <ul>
                <li>Python</li>
                <li>Django</li>
                <li>PostgreSQL</li>
              </ul>
            </td>
            <td></td>
            <tr></tr>
            <td className="table-name">Sanka Darshana</td>
            <td>
              <a href="https://github.com/SankaD">GitHub</a>
            </td>
            <td>
              <ul>
                <li>Python</li>
                <li>Django</li>
                <li>PostgreSQL</li>
              </ul>
            </td>
            <td></td>
            <tr>
              <td className="table-name">Ash</td>
              <td>
                <a href="https://github.com/trevelyan">GitHub</a>
              </td>
              <td>
                <ul>
                  <li>JavaScript</li>
                  <li>React</li>
                  <li>Node.js</li>
                </ul>
              </td>
              <td>0x55a6e3f7B2b164d162D2E32DFB22840DDC1626dF</td>
            </tr>
            <tr>
              <td className="table-name">Umair Khan</td>
              <td>
                <a href="https://twitter.com/umairkhannn">GitHub</a>
              </td>
              <td>
                <ul>
                  <li>JavaScript</li>
                  <li>React</li>
                  <li>Node.js</li>
                </ul>
              </td>
              <td></td>
            </tr>
            <tr>
              <td className="table-name">Saito Kitties</td>
              <td>
                <a href="https://twitter.com/KittiesSaito">GitHub</a>
              </td>
              <td>
                <ul>
                  <li>JavaScript</li>
                  <li>React</li>
                  <li>Node.js</li>
                </ul>
              </td>
              <td></td>
            </tr>
            <tr>
              <td className="table-name">Seanybitcoins</td>
              <td>
                <a href="https://github.com/seanybitcoins">GitHub</a>
              </td>
              <td>
                <ul>
                  <li>JavaScript</li>
                  <li>React</li>
                  <li>NextJS</li>
                </ul>
              </td>
              <td>0x5AB461A69879379b31de56539Ef15afC97520A7a</td>
            </tr>
            <tr>
              <td className="table-name">0xluminous</td>
              <td>
                <a href="https://github.com/0xluminous">GitHub</a>
              </td>
              <td>
                <ul>
                  <li>JavaScript</li>
                  <li>React</li>
                  <li>Node.js</li>
                </ul>
              </td>
              <td></td>
            </tr>
            <tr>
              <td className="table-name">L.Empereur </td>
              <td>
                <a href="https://twitter.com/l_empereur_fr">GitHub</a>
              </td>
              <td>
                <ul>
                  <li>https://saito-ticker.netlify.app</li>
                  <li></li>
                  <li>Node.js</li>
                </ul>
              </td>
              <td></td>
            </tr>
            <tr>
              <td className="table-name">Pawel Pawlak</td>
              <td>
                <a href="https://twitter.com/pawelpawlak14">GitHub</a>
              </td>
              <td>
                <ul>
                  <li>JavaScript</li>
                  <li>React</li>
                  <li>Node.js</li>
                </ul>
              </td>
              <td></td>
            </tr>
            <tr>
              <td className="table-name">Davik stone</td>
              <td>
                <a href="https://github.com/davikstone2">GitHub</a>
              </td>
              <td>
                <ul>
                  <li>JavaScript</li>
                  <li>React</li>
                  <li>Node.js</li>
                </ul>
              </td>
              <td></td>
            </tr>
          </tbody>
        </table>
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" target="_blank" rel="noopener noreferrer">
          Made with ❤️ by Seanybitcoins 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
