import { ConnectButton } from "@rainbow-me/rainbowkit";
import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import getUsdPrice from "../api/api";
const address = "0xfa14fa6958401314851a17d6c5360ca29f74b57b";

const Home = () => {
  const [usdPrice, setUsdPrice] = useState(null);

  useEffect(() => {
    getUsdPrice(address).then(setUsdPrice);
  }, []);

  return (
    <div>
      <Head>
        <title>RainbowKit App</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        {/* Title  */}
        <h1 className={styles.title}>
          Welcome to DONATE2DEVS. Donate with any erc20 tokens. As simple as
          connect and donate.
        </h1>

        {/* Community Address */}
        <div className={styles.contractAddress}>
          <span>Community Address: </span>
          <a
            target="_blank"
            href="https://etherscan.io/address/0x5AB461A69879379b31de56539Ef15afC97520A7a"
          >
            0x94d0b12c651f281566bb415889f703e112027c8a
          </a>
        </div>

        {/* Community Address */}
        <div className={styles.contractAddress}>
          <span>Price of Saito: </span>
          {usdPrice ? (
            <p>
            The USD price for {address} is <span> $ {usdPrice}</span>
          </p>
          ) : (
            <p>Loading USD price...</p>
          )}
        </div>

        <h2>| SAITO DEVS |</h2>

        <table className={styles.table}>
          <thead>
            <tr>
              <th className={styles.tableHead}>Name</th>
              <th className={styles.tableHead}>Social</th>
              <th className={styles.tableHead}>Role</th>
              <th className={styles.tableHead}>Erc address</th>
            </tr>
          </thead>

          <tbody>
            <tr>
              <td className={styles.tableData}>D Lancashire</td>
              <td className={styles.tableData}>
                <a href="https://github.com/trevelyan">GitHub</a>
              </td>
              <td className={styles.tableData}>
                <ul>
                  <li>Founder</li>
                  <li>Red Square</li>
                  <li>Arcade</li>
                </ul>
              </td>
              <td className={styles.tableData}>
                0x94d0b12c651f281566bb415889f703e112027c8a
              </td>
            </tr>

            <tr>
              <td className={styles.tableData}>R Parris</td>
              <td className={styles.tableData}>
                <a href="https://github.com/arpee">GitHub</a>
              </td>
              <td className={styles.tableData}>
                <ul>
                  <li>Founder</li>
                  <li>Redsquare</li>
                  <li>tech</li>
                </ul>
              </td>
              <td className={styles.tableData}>
                0x94d0b12c651f281566bb415889f703e112027c8a
              </td>
            </tr>

            <tr>
              <td className={styles.tableData}>escapedcat</td>
              <td className={styles.tableData}>
                <a href="https://github.com/escapedcat?tab=repositories">
                  GitHub
                </a>
              </td>
              <td className={styles.tableData}>
                <ul>
                  <li>Python</li>
                  <li>Django</li>
                  <li>PostgreSQL</li>
                </ul>
              </td>
              <td className={styles.tableData}>
                0x94d0b12c651f281566bb415889f703e112027c8a
              </td>
            </tr>

            <tr>
              <td className={styles.tableData}>Ramses</td>
              <td className={styles.tableData}>
                <a href="https://github.com/Ramcas42">GitHub</a>
              </td>
              <td className={styles.tableData}>
                <ul>
                  <li>Python</li>
                  <li>Django</li>
                  <li>PostgreSQL</li>
                </ul>
              </td>
              <td className={styles.tableData}>
                0x94d0b12c651f281566bb415889f703e112027c8a
              </td>
            </tr>

            <tr>
              <td className={styles.tableData}>Sanka Darshana</td>
              <td className={styles.tableData}>
                <a href="https://github.com/SankaD">GitHub</a>
              </td>
              <td className={styles.tableData}>
                <ul>
                  <li>Python</li>
                  <li>Django</li>
                  <li>PostgreSQL</li>
                </ul>
              </td>
              <td className={styles.tableData}>
                0x94d0b12c651f281566bb415889f703e112027c8a
              </td>
            </tr>

            <tr>
              <td className={styles.tableData}>Ash</td>
              <td className={styles.tableData}>
                <a href="https://twitter.com/devengineoz">GitHub</a>
              </td>
              <td className={styles.tableData}>
                <ul>
                  <li>JavaScript</li>
                  <li>React Native</li>
                  <li>Mobile App dev</li>
                  <li>HTML</li>
                  <li>Express JS</li>
                </ul>
              </td>
              <td className={styles.tableData}>
                0x55a6e3f7B2b164d162D2E32DFB22840DDC1626dF
              </td>
            </tr>

            <tr>
              <td className={styles.tableData}>Umair Khan</td>
              <td className={styles.tableData}>
                <a href="https://twitter.com/umairkhannn">GitHub</a>
              </td>
              <td className={styles.tableData}>
                <ul>
                  <li>JavaScript</li>
                  <li>React</li>
                  <li>Node.js</li>
                </ul>
              </td>
              <td className={styles.tableData}>
                0x94d0b12c651f281566bb415889f703e112027c8a
              </td>
            </tr>
            <tr>
              <td className={styles.tableData}>Saito Kitties</td>
              <td className={styles.tableData}>
                <a href="https://twitter.com/KittiesSaito">GitHub</a>
              </td>
              <td className={styles.tableData}>
                <ul>
                  <li>JavaScript</li>
                  <li>React</li>
                  <li>Node.js</li>
                </ul>
              </td>
              <td className={styles.tableData}>
                0x94d0b12c651f281566bb415889f703e112027c8a
              </td>
            </tr>
            <tr>
              <td className={styles.tableData}>Seanybitcoins</td>
              <td className={styles.tableData}>
                <a href="https://github.com/seanybitcoins">GitHub</a>
              </td>
              <td className={styles.tableData}>
                <ul>
                  <li>JavaScript</li>
                  <li>React</li>
                  <li>NextJS</li>
                </ul>
              </td>
              <td className={styles.tableData}>
                0x5AB461A69879379b31de56539Ef15afC97520A7a
              </td>
            </tr>
            <tr>
              <td className={styles.tableData}>0xluminous</td>
              <td className={styles.tableData}>
                <a href="https://github.com/0xluminous">GitHub</a>
              </td>
              <td className={styles.tableData}>
                <ul>
                  <li>JavaScript</li>
                  <li>React</li>
                  <li>Node.js</li>
                </ul>
              </td>
              <td className={styles.tableData}>
                0x94d0b12c651f281566bb415889f703e112027c8a
              </td>
            </tr>
            <tr>
              <td className={styles.tableData}>L.Empereur</td>
              <td className={styles.tableData}>
                <a href="https://twitter.com/l_empereur_fr">GitHub</a>
              </td>
              <td className={styles.tableData}>
                <ul>
                  <li>https://saito-ticker.netlify.app</li>
                  <li>Node.js</li>
                  <li>Node.js</li>
                </ul>
              </td>
              <td className={styles.tableData}>
              0x0311fCA1fe11393d6d0cAa765968837f8bc07C09
              </td>
            </tr>
            <tr>
              <td className={styles.tableData}>Pawel Pawlak</td>
              <td className={styles.tableData}>
                <a href="https://twitter.com/pawelpawlak14">GitHub</a>
              </td>
              <td className={styles.tableData}>
                <ul>
                  <li>JavaScript</li>
                  <li>React</li>
                  <li>Node.js</li>
                </ul>
              </td>
              <td className={styles.tableData}>
              0x6429CdF7C49A1242baA69a6591204CC7c7eD666C
              </td>
            </tr>
            <tr>
              <td className={styles.tableData}>Davik stone</td>
              <td className={styles.tableData}>
                <a href="https://github.com/davikstone2">GitHub</a>
              </td>
              <td className={styles.tableData}>
                <ul>
                  <li>JavaScript</li>
                  <li>React</li>
                  <li>Node.js</li>
                </ul>
              </td>
              <td className={styles.tableData}>
                0x94d0b12c651f281566bb415889f703e112027c8a
              </td>
            </tr>
          </tbody>
        </table>
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" target="_blank" rel="noopener noreferrer">
          Made with ❤️ by Seanybitcoins 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
